version: '3.8'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    
    postgres-data:
        image: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=docker
        volumes:
            - ${PWD}/postgres:/var/lib/postgresql/data
        ports:
            - "5435:5432"
    
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        ports:
            - 9200:9200
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        depends_on:
            - elastic
        ports:
            - 5601:5601
        environment:
        xpack.security.enabled: "false"
        discovery.type: "single-node"
        ELASTICSEARCH_HOSTS: "http://elastic:9200"

    webserver:
        image: neylsoncrepalde/airflow-docker:latest
        restart: always
        depends_on:
            - postgres
            - elastic
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # - PYTHON_DEPS="elasticsearch eland"
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - ./requirements.txt:/usr/local/airflow/requirements.txt
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
